### ISSUE TITLE
Integrate HEP funding data

### ISSUE THREAD

**Issue by mbaumer** [justinvasel/WHIPS#148]
I just took a look at the WHIPS website -- it looks amazing! (I missed the trip last year so I haven't used it before).
A few years ago I made a website (https://mbaumer.github.io/us_hep_funding/) to summarize the HEP-related funding grants that have gone to various districts/states (see eg. https://mbaumer.github.io/us_hep_funding/states/IL/). We've used this as supplemental information for a few previous trips, but I think it would be great to centralize by adding this information to the WHIPS system.

I've forked your repo and am happy to implement the changes. Do you think it would be better to include a link to my existing pages or display the info on each legislator's page below the committee information?

**Comment by justinvasel** [comment]
Hi, Mike. Thanks for getting in touch and for your nice comments!

I'm glad you mentioned this because it's something that we've discussed before. We would love to see an implementation of this built in to WHIPS on preferably available on both the legislator's page (what we call the 'member' page) and the meeting page.

As far as implementation goes, we could probably make a new database table to hold the text of the report for each office as a BLOB type, along with the member ID with which it is associated. That would at least be the easiest path as far as the DB goes, but happy to entertain other suggestions.

Thanks so much for volunteering! I've assigned the issue to you, and please don't hesitate to reach out if you have questions. I can also send you sample data from the members table of the DB if that would be useful.

Cheers.

**Comment by FernandaPsihas** [comment]
I have a question regarding this. How does the info on that page get updated every year? Some instructions accompanying the implementation would be great to leave for posterity.

**Comment by mbaumer** [comment]
@justinvasel I have my own ProPublica API key, so I'm just using your app/Scripts/CongressInfo.py to populate the members table myself. I'm thinking I will just edit this script to connect the funding data to the members table. As far as the funding info db, I'll give your BLOB scheme a try first since it should be the most straightforward way to implement this.

@FernandaPsihas Good call! Currently, I manually download some files every year from https://science.energy.gov/universities/sc-in-your-state/ and usaspending.gov and run a script that ingests them and updates my webpages automatically, but I will automate the download process as well so that it can be a one-script process every year.
